---

- name: Manage Nexus container server
  hosts: nexus
  tasks:
    - name: "Build hosts file"
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ item }}.{{ ansible_domain }}"
        state: present
      when: hostvars[item].ansible_default_ipv4.address is defined
      loop: "{{ groups['all'] }}"

    - name: Include buissetemmanuel.container
      ansible.builtin.include_role:
        name: container
