---

users_groups:
  - name: nexusug
  - name: nexusugs
  - name: nexusugl
  - name: nexusugal
users_users:
  - name: nexusuo
    group: nexusug
    create_home: true
  - name: nexusuos
    group: nexusugs
    create_home: true
    groups: nexusugl, wheel
  - name: nexusual
    group: nexusugal
    groups: nexusugl

container_user_owner: nexusuo
container_user_group: nexusug
container_user_group_logs: nexusugl
container_user_owner_service: nexusuos
container_user_group_service: nexusugs

container_pod_name: nexus_pod

container_pod_containers:
  - name: nexus
    description: "Nexus server container"
    image_name: docker.io/sonatype/nexus3
    image_tag: 3.64.0
    image_pull_policy: IfNotPresent
    resources:
      limits:
        memory: "4Gi"
        cpu: "1000m"
      requests:
        memory: "2Gi"
        cpu: "500m"
    securityContext:
      runAsUser: 0
    ports:
      - containerPort: 8081
        hostPort: 8081
        protocol: TCP
    volumeMounts:
      - mountPath: /nexus-data:rw,z
        name: nexus-data

nexus_pod_data_dir: "{{ container_pod_home_dir }}/nexus-data"

container_directories:
  - path: "{{ nexus_pod_data_dir }}"
    owner: "{{ container_user_owner_service }}"
    group: "{{ container_user_group_service }}"
    mode: "{{ container_directories_mode }}"

container_pod_volumes:
  - name: nexus-data
    hostPath:
      path: "{{ nexus_pod_data_dir }}"
      type: DirectoryOrCreate
